### ISSUE TITLE
Method preferences

### ISSUE THREAD

**Issue by jbodah** [backupify/backupify_styleguides#14]
I recommend we pick some standard methods to use. Some methods have aliases. For example, `map` and `collect` are aliased, but I feel like we should only use one or the other

From the default rubocop config:

``` yml
# Align with the style guide.
Style/CollectionMethods:
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'
```
